name: CI to ECR

on:
  push:
    branches:
      - master

jobs:
  request-approval:
    runs-on: ubuntu-latest
    outputs:
      approved: ${{ steps.approval.outputs.approved }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Request approval
        id: approval
        uses: reviewdog/action-wait-approval@v1
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          message: "🚀 New commit pushed to master! Approve to start ECR deployment."
          approvers: "*"
          timeout_minutes: 30
  
  build-and-push:
    needs: request-approval
    if: ${{ needs.request-approval.outputs.approved == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set commit SHA as IMAGE_TAG
        id: vars
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

      - name: Build Docker image
        run: |
          docker build -t algoreview/fe:${{ env.IMAGE_TAG }} .
          docker tag algoreview/fe:${{ env.IMAGE_TAG }} 165304734991.dkr.ecr.ap-northeast-1.amazonaws.com/algoreview/fe:${{ env.IMAGE_TAG }}

      - name: Push to ECR
        run: |
          docker push 165304734991.dkr.ecr.ap-northeast-1.amazonaws.com/algoreview/fe:${{ env.IMAGE_TAG }}
